package com.company.sec13f.parser.web;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;

/**
 * Servlet to handle the home page
 */
public class HomeServlet extends HttpServlet {
    
    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        // Set response content type
        resp.setContentType("text/html");
        resp.setCharacterEncoding("UTF-8");
        
        PrintWriter out = resp.getWriter();
        
        out.println("<!DOCTYPE html>");
        out.println("<html>");
        out.println("<head>");
        out.println("    <title>SEC 13F Parser</title>");
        out.println("    <meta charset=\"UTF-8\">");
        out.println("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
        out.println("    <style>");
        out.println("        body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background-color: #f5f5f5; }");
        out.println("        .container { max-width: 1200px; margin: 0 auto; background-color: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }");
        out.println("        h1 { color: #333; text-align: center; }");
        out.println("        .search-box { text-align: center; margin: 20px 0; }");
        out.println("        input[type='text'] { padding: 10px; font-size: 16px; width: 300px; border: 1px solid #ddd; border-radius: 4px; }");
        out.println("        button { padding: 10px 20px; font-size: 16px; background-color: #007bff; color: white; border: none; border-radius: 4px; cursor: pointer; }");
        out.println("        button:hover { background-color: #0056b3; }");
        out.println("        table { width: 100%; border-collapse: collapse; margin-top: 20px; }");
        out.println("        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }");
        out.println("        th { background-color: #f8f9fa; font-weight: bold; }");
        out.println("        tr:hover { background-color: #f5f5f5; }");
        out.println("        .loading { text-align: center; padding: 20px; }");
        out.println("        .error { color: red; text-align: center; padding: 20px; }");
        out.println("        .hidden { display: none; }");
        out.println("    </style>");
        out.println("</head>");
        out.println("<body>");
        out.println("    <div class=\"container\">");
        out.println("        <h1>SEC 13F Holdings Explorer</h1>");
        out.println("        <div class=\"search-box\">");
        out.println("            <input type=\"text\" id=\"cikInput\" placeholder=\"Enter CIK (e.g., 0001524258 for Alibaba)\" value=\"0001524258\">");
        out.println("            <button onclick=\"searchFilings()\">Search</button>");
        out.println("            <a href=\"/analysis.html\" style=\"margin-left: 20px; padding: 10px 20px; background-color: #28a745; color: white; text-decoration: none; border-radius: 4px;\">Advanced Analysis</a>");
        out.println("            <a href=\"/scraping.html\" style=\"margin-left: 10px; padding: 10px 20px; background-color: #dc3545; color: white; text-decoration: none; border-radius: 4px;\">Data Scraping</a>");
        out.println("        </div>");
        out.println("        <div id=\"loading\" class=\"loading hidden\">Loading...</div>");
        out.println("        <div id=\"error\" class=\"error hidden\"></div>");
        out.println("        <table id=\"resultsTable\" class=\"hidden\">");
        out.println("            <thead>");
        out.println("                <tr>");
        out.println("                    <th>Issuer Name</th>");
        out.println("                    <th>CUSIP</th>");
        out.println("                    <th>Shares</th>");
        out.println("                    <th>Value ($1000)</th>");
        out.println("                    <th>Filing Date</th>");
        out.println("                    <th>Accession Number</th>");
        out.println("                </tr>");
        out.println("            </thead>");
        out.println("            <tbody id=\"resultsBody\">");
        out.println("            </tbody>");
        out.println("        </table>");
        out.println("    </div>");
        out.println("    <script>");
        out.println("        function searchFilings() {");
        out.println("            const cik = document.getElementById('cikInput').value.trim();");
        out.println("            if (!cik) {");
        out.println("                showError('Please enter a CIK number');");
        out.println("                return;");
        out.println("            }");
        out.println("            ");
        out.println("            // Show loading indicator");
        out.println("            document.getElementById('loading').classList.remove('hidden');");
        out.println("            document.getElementById('error').classList.add('hidden');");
        out.println("            document.getElementById('resultsTable').classList.add('hidden');");
        out.println("            ");
        out.println("            // Fetch data from the server");
        out.println("            fetch('/search?cik=' + encodeURIComponent(cik))");
        out.println("                .then(response => response.json())");
        out.println("                .then(data => {");
        out.println("                    document.getElementById('loading').classList.add('hidden');");
        out.println("                    if (data.error) {");
        out.println("                        showError(data.error);");
        out.println("                    } else {");
        out.println("                        displayResults(data.holdings);");
        out.println("                    }");
        out.println("                })");
        out.println("                .catch(error => {");
        out.println("                    document.getElementById('loading').classList.add('hidden');");
        out.println("                    showError('Error fetching data: ' + error.message);");
        out.println("                });");
        out.println("        }");
        out.println("        ");
        out.println("        function displayResults(holdings) {");
        out.println("            const tbody = document.getElementById('resultsBody');");
        out.println("            tbody.innerHTML = '';");
        out.println("            ");
        out.println("            if (!holdings || holdings.length === 0) {");
        out.println("                showError('No holdings found for this CIK');");
        out.println("                return;");
        out.println("            }");
        out.println("            ");
        out.println("            holdings.forEach(holding => {");
        out.println("                const row = document.createElement('tr');");
        out.println("                row.innerHTML = `");
        out.println("                    <td>${escapeHtml(holding.holding.nameOfIssuer)}</td>");
        out.println("                    <td>${escapeHtml(holding.holding.cusip)}</td>");
        out.println("                    <td>${formatNumber(holding.holding.shares)}</td>");
        out.println("                    <td>$${formatCurrency(holding.holding.value)}</td>");
        out.println("                    <td>${formatDate(holding.filingDate)}</td>");
        out.println("                    <td>${escapeHtml(holding.accessionNumber)}</td>");
        out.println("                `;");
        out.println("                tbody.appendChild(row);");
        out.println("            });");
        out.println("            ");
        out.println("            document.getElementById('resultsTable').classList.remove('hidden');");
        out.println("        }");
        out.println("        ");
        out.println("        function showError(message) {");
        out.println("            const errorDiv = document.getElementById('error');");
        out.println("            errorDiv.textContent = message;");
        out.println("            errorDiv.classList.remove('hidden');");
        out.println("        }");
        out.println("        ");
        out.println("        function escapeHtml(text) {");
        out.println("            if (!text) return '';");
        out.println("            const map = {");
        out.println("                '&': '&amp;',");
        out.println("                '<': '&lt;',");
        out.println("                '>': '&gt;',");
        out.println("                '\"': '&quot;',");
        out.println("                \"'\": '&#039;'");
        out.println("            };");
        out.println("            return text.replace(/[&<>'\"]/g, m => map[m]);");
        out.println("        }");
        out.println("        ");
        out.println("        function formatNumber(number) {");
        out.println("            if (number === null || number === undefined) return 'N/A';");
        out.println("            return new Intl.NumberFormat().format(number);");
        out.println("        }");
        out.println("        ");
        out.println("        function formatCurrency(value) {");
        out.println("            if (value === null || value === undefined) return '0.00';");
        out.println("            return new Intl.NumberFormat('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(value);");
        out.println("        }");
        out.println("        ");
        out.println("        function formatDate(dateString) {");
        out.println("            if (!dateString) return 'N/A';");
        out.println("            const date = new Date(dateString);");
        out.println("            return date.toLocaleDateString('en-US');");
        out.println("        }");
        out.println("        ");
        out.println("        // Search automatically when the page loads with the default CIK");
        out.println("        window.onload = function() {");
        out.println("            searchFilings();");
        out.println("        };");
        out.println("    </script>");
        out.println("</body>");
        out.println("</html>");
        out.close();
    }
}